### ISSUE TITLE
Unable to build on arm64 with tflite backend

### ISSUE THREAD

**Issue by boxerab** [RidgeRun/r2inference#57]
I compiled tflite natively using the [following link](https://www.tensorflow.org/lite/guide/build_arm64)
and copied the static library into `/usr/lib/aarch64-linux-gnu/`

I then ran

` ./autogen.sh --enable-tflite --prefix /usr/ --libdir /usr/lib/aarch64-linux-gnu/` on master branch 
of r2inference, but I get these errors:
```
configure: *** checking feature: tflite ***
checking for TfLiteTypeGetName in -ltensorflow-lite... yes
checking tensorflow/lite/model.h usability... no
checking tensorflow/lite/model.h presence... no
checking for tensorflow/lite/model.h... no
configure: error: Couldn't find tensorflow-lite
```

I guess I also need to put the tensorflow headers in prefix ?

**Comment by michaelgruner** [comment]
can you share your `config.log`?

**Comment by michaelgruner** [comment]
If you built from source you may likely be missing the include paths to TF Lite headers. Try something like:


```bash
./autogen.sh --prefix /usr/ --libdir /usr/lib/x86_64-linux-gnu/ CXXFLAGS=”-I$(TensorflowPath) -I $(TensorflowPath)/tensorflow/lite/tools/make/downloads/flatbuffers/include -pthread”
```

**Comment by boxerab** [comment]
Thanks, I am building on arm64 armbian, so this is what finally worked:

```
export CPLUS_INCLUDE_PATH=${TensorflowPath} 
sudo apt install flatbuffers-compiler-dev libflatbuffers-dev  
./autogen.sh --prefix /usr/ --libdir /usr/lib/x86_64-linux-gnu/ CXXFLAGS="-pthread" --enable-tflite 
make 
make check 
sudo make install
```
