### ISSUE TITLE
make check fails: libr2inference-0.0.so: undefined reference to `pthread_create'

### ISSUE THREAD

**Issue by boxerab** [RidgeRun/r2inference#69]
Hello!

On master:

I followed the steps [here](https://developer.ridgerun.com/wiki/index.php?title=R2Inference/Getting_started/Building_the_library) for x86, but I get these errors:

```
/bin/bash ../../../../libtool  --tag=CXX   --mode=link g++ -Werror -Wall -O0 -ggdb3     -g -O2  -ltensorflow-lite -lstdc++ -lCppUTest -lCppUTestExt  ../../../../r2i/libr2inference-0.0.la  -o loader loader.o  
libtool: link: g++ -Werror -Wall -O0 -ggdb3 -g -O2 -o .libs/loader loader.o  -ltensorflow-lite -lstdc++ -lCppUTest -lCppUTestExt ../../../../r2i/.libs/libr2inference-0.0.so
/usr/bin/ld: ../../../../r2i/.libs/libr2inference-0.0.so: undefined reference to `pthread_create'
/usr/bin/ld: ../../../../r2i/.libs/libr2inference-0.0.so: undefined reference to `pthread_join'
collect2: error: ld returned 1 exit status
```

So, it looks like pthreads library is not getting linked.

**Comment by boxerab** [comment]
I solved this with:

`export LDFLAGS=" -pthread -lpthread" `

but the autogen should really be taking care of this.

**Comment by michaelgruner** [comment]
@lumurillo has this assigned. Luis please reply to this thread with the fix.

**Comment by lumurillo** [comment]
Hello @boxerab. We recently merged a fix for this issue into master. Could you confirm your problem is now solved?

**Comment by boxerab** [comment]
Thanks, fixed now.
